<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>warnings</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mingley.Application\Mingley.Application.csproj" />
    <ProjectReference Include="..\Mingley.Domain\Mingley.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"    Version="8.0.4" />
    <PackageReference Include="BCrypt.Net-Next"                        Version="4.0.3" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens"         Version="8.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt"        Version="8.0.1" />
  </ItemGroup>
</Project>
